### ISSUE TITLE
Nueva entidad Mesa

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p2_g1_sf#2]
#### Crear una entidad en Spring Boot con las siguientes especificaciones:

1. La entidad debe estar ubicada dentro del paquete `entity`.
2. Todos los atributos deben ser privados.
3. Se deben generar los métodos getters y setters para todos los atributos.
4. La entidad debe contener una clave primaria con nombre `id`, de tipo de dato `Long`.
5. Evitar definir constructores a menos que sean necesarios.
6. Evitar sobrecargar el método `toString()` a menos que sea necesario.
7. Evitar el uso de las anotaciones `@Table` o `@Column` a menos que sea necesario.
8. En el caso de que un atributo sea de un tipo de dato de una clase que aún no existe, crearlo temporalmente con tipo de dato `Long`.

#### Captura de Pantalla

Por favor, proporciona una captura de pantalla del diagrama de tablas generado al iniciar la aplicación, mostrando la estructura de las tablas que se han creado.

#### Atributos de la entidad Mesa

* Id
* Capacidad
* Estado (ocupado - Disponible)

**Comment by JenniArabel** [comment]
Entidad MESA subida
