### ISSUE TITLE
Relacion Factura Empleado

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p2_g1_sf#23]
**Descripción:** Crear una relación @ManyToOne entre la entidad `Factura` y la entidad `Empleado`, suponiendo que un empleado puede generar varias facturas.

**Instrucciones:**

1. Añadir un campo de `Empleado` en la entidad `Factura`.
2. Utilizar la anotación `@ManyToOne` en la entidad `Factura` y `@OneToMany` en la entidad `Empleado`.

**Evidencia en pull request:** Incluir una captura de pantalla del diagrama de la base de datos que muestra la relación. No añadas todos los archivos con `git add .`

**Comment by JenniArabel** [comment]
Relacion Factura Empleado creada

![Relacion Factura-Empleado](https://github.com/ahumadamob/2024_gc_p2_g1_sf/assets/119452050/c598cca2-3cc5-4f83-8156-988d409fe6e7)

**Comment by ahumadamob** [comment]
Tienes que crear el Pull Request
