### ISSUE TITLE
Persistencia Avanzada de Mesa

### ISSUE THREAD

**Issue by AraMirta** [ahumadamob/2024_gc_p2_g1_sf#48]
#### Descripción:

Desarrollar un controlador en Spring Boot para gestionar una entidad (por ejemplo, Producto) con las siguientes operaciones:

1. **Buscar todos los elementos**:
   - Implementar un método que permita obtener todos los elementos.
   - Si no se encuentran resultados, devolver un mensaje indicando que no hay datos disponibles.

2. **Buscar por ID**:
   - Implementar un método que permita buscar un elemento por su ID.
   - Si no se encuentra el ID, devolver un mensaje indicando que el elemento no existe.

3. **Crear un nuevo elemento**:
   - Implementar un método para crear un nuevo elemento.
   - Si el ID ya existe, devolver un mensaje de error.

4. **Actualizar un elemento existente**:
   - Implementar un método que permita actualizar un elemento.
   - Si el ID del elemento no existe, devolver un mensaje indicando que no se puede actualizar un elemento inexistente.

5. **Eliminar un elemento**:
   - Implementar un método que permita eliminar un elemento por su ID.
   - Si el ID no existe, devolver un mensaje indicando que no se pudo encontrar el elemento para eliminar.

6. **Verificar existencia de un elemento**:
   - Crear un método llamado `exists` que verifique si un elemento existe en la base de datos según su ID.

#### Requisitos:

- Utilizar un **DTO (Data Transfer Object)** que contenga los siguientes atributos:
   - `estado`: Indica si la operación fue exitosa o fallida.
   - `mensaje`: Contiene un mensaje de error o éxito.
   - `objeto`: El objeto que se ha perdido o consultado.

- **Nota**: Se permite usar **ResponseEntity**, pero no es obligatorio.

#### Documentación:

- Asegurarse de incluir comentarios de código fuente que expliquen los siguientes conceptos:
   - Un **ejemplo de encapsulamiento** dentro de una clase (como getters y setters).
   - Un **ejemplo de instancia de objeto** en alguna parte del controlador o servicio.
   - Un **ejemplo de inicialización de objetos**.

#### Pruebas:

Como parte de la entrega, adjuntar capturas de pantalla correspondientes a las pruebas realizadas con **Postman** para cada una de las siguientes situaciones:
- Búsqueda exitosa de todos los elementos.
- Búsqueda por ID exitosa.
- Búsqueda por ID fallida.
- Creación de un nuevo elemento.
- Intento de creación de un elemento con ID ya existente.
- Actualización exitosa.
- Intento de actualización de un elemento inexistente.
- Eliminación exitosa.
- Intento de eliminación de un elemento inexistente.
- Verificación de existencia de un elemento.

**Comment by FacundoGiannone** [comment]
Persistencia avanzada terminada

PRUEBAS:
Búsqueda exitosa de todos los elementos.
![image](https://github.com/user-attachments/assets/ac2b762b-f3c2-4989-a728-4b57aa3108e0)

Búsqueda por ID exitosa.
![image](https://github.com/user-attachments/assets/d30a643a-a92b-4c10-a092-02f7bc455e70)

Búsqueda por ID fallida.
![image](https://github.com/user-attachments/assets/6278854e-6c21-464f-b7d6-35e359a83c76)

Creación de un nuevo elemento.
![image](https://github.com/user-attachments/assets/f2eb6336-5e32-4abb-9d1b-fe5bbb520379)

Intento de creación de un elemento con ID ya existente.
![image](https://github.com/user-attachments/assets/706ae6e2-fc12-4044-b878-2648fb9e04e3)

Actualización exitosa.
![image](https://github.com/user-attachments/assets/56c37b28-be18-4321-bf9d-578ed5773dab)

Intento de actualización de un elemento inexistente.
![image](https://github.com/user-attachments/assets/46738dd5-0b67-43b4-9952-59ca54b2510c)

Eliminación exitosa.
![image](https://github.com/user-attachments/assets/de7ecdf1-8def-4460-8bd5-76776984d65c)

Intento de eliminación de un elemento inexistente.
![image](https://github.com/user-attachments/assets/c6cd3636-750a-4983-8e7d-b85681e6b9b8)
