### ISSUE TITLE
Persistencia Avanzada de Factura

### ISSUE THREAD

**Issue by AraMirta** [ahumadamob/2024_gc_p2_g1_sf#49]
#### Descripción:

Desarrollar un controlador en Spring Boot para gestionar una entidad (por ejemplo, Producto) con las siguientes operaciones:

1. **Buscar todos los elementos**:
   - Implementar un método que permita obtener todos los elementos.
   - Si no se encuentran resultados, devolver un mensaje indicando que no hay datos disponibles.

2. **Buscar por ID**:
   - Implementar un método que permita buscar un elemento por su ID.
   - Si no se encuentra el ID, devolver un mensaje indicando que el elemento no existe.

3. **Crear un nuevo elemento**:
   - Implementar un método para crear un nuevo elemento.
   - Si el ID ya existe, devolver un mensaje de error.

4. **Actualizar un elemento existente**:
   - Implementar un método que permita actualizar un elemento.
   - Si el ID del elemento no existe, devolver un mensaje indicando que no se puede actualizar un elemento inexistente.

5. **Eliminar un elemento**:
   - Implementar un método que permita eliminar un elemento por su ID.
   - Si el ID no existe, devolver un mensaje indicando que no se pudo encontrar el elemento para eliminar.

6. **Verificar existencia de un elemento**:
   - Crear un método llamado `exists` que verifique si un elemento existe en la base de datos según su ID.

#### Requisitos:

- Utilizar un **DTO (Data Transfer Object)** que contenga los siguientes atributos:
   - `estado`: Indica si la operación fue exitosa o fallida.
   - `mensaje`: Contiene un mensaje de error o éxito.
   - `objeto`: El objeto que se ha perdido o consultado.

- **Nota**: Se permite usar **ResponseEntity**, pero no es obligatorio.

#### Documentación:

- Asegurarse de incluir comentarios de código fuente que expliquen los siguientes conceptos:
   - Un **ejemplo de encapsulamiento** dentro de una clase (como getters y setters).
   - Un **ejemplo de instancia de objeto** en alguna parte del controlador o servicio.
   - Un **ejemplo de inicialización de objetos**.

#### Pruebas:

Como parte de la entrega, adjuntar capturas de pantalla correspondientes a las pruebas realizadas con **Postman** para cada una de las siguientes situaciones:
- Búsqueda exitosa de todos los elementos.
- Búsqueda por ID exitosa.
- Búsqueda por ID fallida.
- Creación de un nuevo elemento.
- Intento de creación de un elemento con ID ya existente.
- Actualización exitosa.
- Intento de actualización de un elemento inexistente.
- Eliminación exitosa.
- Intento de eliminación de un elemento inexistente.
- Verificación de existencia de un elemento.

**Comment by chulogiamportone** [comment]
![image](https://github.com/user-attachments/assets/41aacc81-1b8a-4bb7-815b-e722f1f0cad6)
![image](https://github.com/user-attachments/assets/4e7b924a-a535-4a14-acd3-29231accdc4e)

![image](https://github.com/user-attachments/assets/d8751521-e9f7-40e8-8e45-a6c1abf2a2de)
![image](https://github.com/user-attachments/assets/018055a2-348a-4b3e-a228-b9f9c6e4b1bf)
![image](https://github.com/user-attachments/assets/a2cfe876-0777-483e-b9e3-3f4db9c400d0)
![image](https://github.com/user-attachments/assets/ccb2fd77-d73d-4db1-9377-be0e3ef2ca1f)
![image](https://github.com/user-attachments/assets/47907156-e204-43bf-8510-d79248755338)

![image](https://github.com/user-attachments/assets/67a01cbf-cb86-4da8-a108-ad6aae90b59b)
![image](https://github.com/user-attachments/assets/44e0a879-75db-4402-a9da-cc3d856bbfee)

**Comment by chulogiamportone** [comment]
![image](https://github.com/user-attachments/assets/1fbd4590-146b-4599-bcf1-4a50e50c28a5)
![image](https://github.com/user-attachments/assets/8f23f735-f429-497c-a98e-0474440a386d)

**Comment by ahumadamob** [comment]
Parece que ya está listo... pero falta que hagas el pull request

**Comment by chulogiamportone** [comment]
Ahí realice el pull request
