### ISSUE TITLE
Persistencia Avanzada de MedioDePago

### ISSUE THREAD

**Issue by AraMirta** [ahumadamob/2024_gc_p2_g1_sf#51]

**Comment by ahumadamob** [comment]
### Ejercicio: Desarrollo de un Controlador en Spring Boot con Manejo de Excepciones

#### Descripción:

Desarrollar un controlador en Spring Boot para gestionar una entidad (por ejemplo, Producto) con las siguientes operaciones:

1. **Buscar todos los elementos**:
   - Implementar un método que permita obtener todos los elementos.
   - Si no se encuentran resultados, devolver un mensaje indicando que no hay datos disponibles.

2. **Buscar por ID**:
   - Implementar un método que permita buscar un elemento por su ID.
   - Si no se encuentra el ID, devolver un mensaje indicando que el elemento no existe.

3. **Crear un nuevo elemento**:
   - Implementar un método para crear un nuevo elemento.
   - Si el ID ya existe, devolver un mensaje de error.

4. **Actualizar un elemento existente**:
   - Implementar un método que permita actualizar un elemento.
   - Si el ID del elemento no existe, devolver un mensaje indicando que no se puede actualizar un elemento inexistente.

5. **Eliminar un elemento**:
   - Implementar un método que permita eliminar un elemento por su ID.
   - Si el ID no existe, devolver un mensaje indicando que no se pudo encontrar el elemento para eliminar.

6. **Verificar existencia de un elemento**:
   - Crear un método llamado `exists` que verifique si un elemento existe en la base de datos según su ID.

#### Requisitos:

- Utilizar un **DTO (Data Transfer Object)** que contenga los siguientes atributos:
   - `estado`: Indica si la operación fue exitosa o fallida.
   - `mensaje`: Contiene un mensaje de error o éxito.
   - `objeto`: El objeto que se ha perdido o consultado.

- **Nota**: Se permite usar **ResponseEntity**, pero no es obligatorio.

#### Documentación:

- Asegurarse de incluir comentarios de código fuente que expliquen los siguientes conceptos:
   - Un **ejemplo de encapsulamiento** dentro de una clase (como getters y setters).
   - Un **ejemplo de instancia de objeto** en alguna parte del controlador o servicio.
   - Un **ejemplo de inicialización de objetos**.

#### Pruebas:

Como parte de la entrega, adjuntar capturas de pantalla correspondientes a las pruebas realizadas con **Postman** para cada una de las siguientes situaciones:
- Búsqueda exitosa de todos los elementos.
- Búsqueda por ID exitosa.
- Búsqueda por ID fallida.
- Creación de un nuevo elemento.
- Intento de creación de un elemento con ID ya existente.
- Actualización exitosa.
- Intento de actualización de un elemento inexistente.
- Eliminación exitosa.
- Intento de eliminación de un elemento inexistente.
- Verificación de existencia de un elemento.

**Comment by alepmont** [comment]
//Ejemplo de encapsulamiento: nombre es private  y no se puede acceder directamente
	// ejemplo del método getter del atributo encapsulado
	// ejemplo del método setter del atributo encapsulado
 
![image](https://github.com/user-attachments/assets/26851d66-d890-45b9-88a0-48b57e2e9999)


		//Ejemplo de instancia de objeto
		//Ejemplo de inicialización de objeto
 
![image](https://github.com/user-attachments/assets/f48cea83-83fb-4b30-a715-a78e1440fecd)


•	Búsqueda exitosa de todos los elementos.
![image](https://github.com/user-attachments/assets/daab6ffd-9617-43f0-be82-e1e771e60b94)

•	Búsqueda por ID exitosa.
![image](https://github.com/user-attachments/assets/e3ea5bb6-0ecd-4b55-adca-c3fbd4254806)

•	Búsqueda por ID fallida.
![image](https://github.com/user-attachments/assets/b77c2224-22d2-48dc-bb23-b30f27c9b07f)
	 
•	Creación de un nuevo elemento.
 
![image](https://github.com/user-attachments/assets/61bdefcb-4a8c-477a-be91-a654761aa4d5)

•	Intento de creación de un elemento con ID ya existente.
![image](https://github.com/user-attachments/assets/9421f28a-6548-46a5-a6af-89f9deb4f2d7)
	 
•	Actualización exitosa.
![image](https://github.com/user-attachments/assets/91287c11-f0b0-4619-889e-f04aea0d6dfd)

•	Intento de actualización de un elemento inexistente.
![image](https://github.com/user-attachments/assets/e43e0a89-acca-480e-9f1f-ba5878517c30)

•	Eliminación exitosa.
![image](https://github.com/user-attachments/assets/b81b0015-80ac-4e4c-bce8-3362ba25bbd5)

•	Intento de eliminación de un elemento inexistente.
![image](https://github.com/user-attachments/assets/6809a573-7bcf-485b-a833-d69266c7f4df)

•	Verificación de existencia de un elemento.
![image](https://github.com/user-attachments/assets/5581d810-5ba4-457b-944b-16ee4150f6cd)
